---
- gem: name=sensu-plugins-disk-checks state=present executable=/opt/sensu/embedded/bin/gem user_install=no state=present

- name: sensu disk check
  copy:
    content='{{ sensu_disk_check | to_nice_json }}'
    dest=/etc/sensu/conf.d/check_disk.json owner=sensu group=sensu mode=0640
  notify:
    - restart sensu client
