---
- apt: name=build-essential state=installed
- gem: name=sensu-plugins-mailer state=present executable=/opt/sensu/embedded/bin/gem user_install=no state=present

- name: sensu mailer config
  copy:
    content='{{ sensu_mail_configuration | to_nice_json }}'
    dest=/etc/sensu/conf.d/mailer.json owner=sensu group=sensu mode=0640
  notify:
    - restart sensu server
